export const UNISTACK_SET_PAGE_TITLE = 'UNISTACK_SET_PAGE_TITLE'
export const UNISTACK_SET_PAGE_BODY_SCRIPTS = 'UNISTACK_SET_PAGE_BODY_SCRIPTS'
export const UNISTACK_SET_DEV_BODY_SCRIPTS = 'UNISTACK_SET_DEV_BODY_SCRIPTS'
export const UNISTACK_APPEND_TO_BODY_SCRIPTS = 'UNISTACK_APPEND_TO_BODY_SCRIPTS'
